// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqG-sP4W4WMl2RD9Oe24xLVZOANjRneUM',
    appId: '1:1039087412201:web:db9267fc0244206412a178',
    messagingSenderId: '1039087412201',
    projectId: 'mynotes-zerihun',
    authDomain: 'mynotes-zerihun.firebaseapp.com',
    storageBucket: 'mynotes-zerihun.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZyjnxzFZLwG13n2b3PEu7opndpOZu4L8',
    appId: '1:1039087412201:android:05d9e629b8805ccd12a178',
    messagingSenderId: '1039087412201',
    projectId: 'mynotes-zerihun',
    storageBucket: 'mynotes-zerihun.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtPTDyHXGF0UlP42m5d78RsJReCbibjyE',
    appId: '1:1039087412201:ios:6ef72df9424af44912a178',
    messagingSenderId: '1039087412201',
    projectId: 'mynotes-zerihun',
    storageBucket: 'mynotes-zerihun.appspot.com',
    iosBundleId: 'com.zerihun.mynotes',
  );
}
